### ISSUE TITLE
Incorporating structural schema information

### ISSUE THREAD

**Issue by overflw** [delftdata/valentine#39]
Dear valentine devs,
I was wondering about losing the structural information found in json / dictionaries when normalizing them into pandas data frames. To my understanding, coma3 would usually use this information in a matching process to improve the results. What do you think about supporting a nested (JSON) data source? I guess one would need to transform it to xml to be able to use it with coma ect.

All the best, and thanks for the great work!

**Comment by chrisk21** [comment]
Hi @overflw  and thanks for your comment and support!

Valentine is a python package designed for supporting matching on tabular datasets only. Support for other file formats such as .json/.xml and for methods that can handle them (like COMA) is not straightforward, thus it can be seen as the goal of another project in the future. However, we could include support for such file formats in a future release, given the demand. And, of course, we are open to any contributions by the community!

**Comment by asteriosk** [comment]
Closing this one! @overflw in case you want to contribute something, we would be happy to guide you through the process.
