### ISSUE TITLE
get_matches fails for Coma when the column has special characters

### ISSUE THREAD

**Issue by AndraIonescu** [delftdata/valentine#42]
Hello, 

I ran Valentine with the Coma matcher 
`valentine_match(df1, df2, Coma(strategy="COMA_OPT"))`
for a dataset which contains columns with special characters like:
`1:00-2:00AM` (that is actually the name of the column) 
and the code failed here: 
https://github.com/delftdata/valentine/blob/37b31035753a1324eafba02bb15f512219055dad/valentine/algorithms/coma/coma.py#L76

**Comment by zhitao-zeng** [comment]
Hi, 
When i try to ran Valentine using the example.py, since my system is Window11, I got an error like this
![image](https://user-images.githubusercontent.com/54173334/194973707-1b10236e-f69f-4f33-af8d-1727514991d4.png)

**Comment by zhitao-zeng** [comment]
> 

Sorry, I solve this problem by install WSL

**Comment by kPsarakis** [comment]
Hi, do you have java (jre) installed?

**Comment by kPsarakis** [comment]
After the colon fix `:` I tested with all special characters, and the only one that could still cause an issue is `.` and ` <-> ` as a single word. Closing this for now.
