### ISSUE TITLE
Run time of Cupid()

### ISSUE THREAD

**Issue by zhitao-zeng** [delftdata/valentine#43]
Hello,

 I am trying to match the feature name in two example data sets with 100 rows and 300 columns. It cost me more than 20 mins but still can't get the output. Is there anything wrong?
![image](https://user-images.githubusercontent.com/54173334/195158824-b1221c62-17bf-4d45-8c28-10063472b1ee.png)

**Comment by kPsarakis** [comment]
Hi, 

Rows should not play a role with `Cupid` since it is a schema-only method. 
Do you have any special characters in your column names? 

It shouldn't take more than 20'. Could you help me reproduce this behavior on our side and attempt a fix?

**Comment by zhitao-zeng** [comment]
The column names look like this and I am not sure if these schema matching algorithems is useful in this case 
![image](https://user-images.githubusercontent.com/54173334/195201187-ab20415a-d58c-4a48-b804-8664d3a94d4d.png)

**Comment by kPsarakis** [comment]
As far as I understand, these are cryptographic hashes of the column names, if you could get the actual column names, then most methods would work. However, if this is impossible, the only algorithm that would work is the `DistributionBased` that works on the row data. 

`JacardLeven` also works on just the row data, but it is a bit slow for your use case.

**Comment by zhitao-zeng** [comment]
Thanks, I can successfully run the DistributionBased in my data by choosing some of the columns, since it still run slow when trying to do with the whole dataset

**Comment by kPsarakis** [comment]
You can also speed up the `DistributionBased` method with the parameter `process_num` (set to 1 by default) that spawns as many processes as you put it to run this method in parallel.
