### ISSUE TITLE
get_matches for distribution based matching fails due to pickled files not refound

### ISSUE THREAD

**Issue by Anphisa** [delftdata/valentine#44]
Hello,

I ran Valentine with the DistributionBased strategy

```
import pandas as pd
from valentine.algorithms import DistributionBased
from valentine import valentine_match

df1 = pd.read_csv("data/Books recommender/book_titles-collaborative_books_df/book_titles.csv", encoding='utf-8')
df2 = pd.read_csv("data/Books recommender/book_titles-collaborative_books_df/collaborative_books_df.csv", encoding='utf-8')

matches = valentine_match(df1, df2, DistributionBased())
```

And I get this error: 
![https://i.postimg.cc/ryr5ZYWP/Unbenannt3.png](https://i.postimg.cc/ryr5ZYWP/Unbenannt3.png)
([WinError 2] The system cannot find the file specified: 'C:\\Users\\xxx\\AppData\\Local\\Temp\\tmptv_b_0v6\\table1title.pkl')

The pickled rank files can not be found again. I can't find the files manually in my AppData folder either.
The csv files come from here: https://www.kaggle.com/datasets/thedevastator/book-recommender-system-itembased

I'm on Windows 10, I've forked valentine and am running it locally. It is up to date with valentine:master today. I haven't made any changes to the DistributionBased code.

**Comment by kPsarakis** [comment]
Hello, thanks a lot for letting us know. We managed to reproduce the issue, and currently working on a fix.

**Comment by kPsarakis** [comment]
I just committed a fix that solved this on our side. It was caused when the `os.path.getsize(file_path)` tried to access a file that was already open, throwing an exception. Let us know if that fixed it

**Comment by Anphisa** [comment]
Hello, thanks for your quick answer! So far, I don't get the error anymore with the fix. Thank you for the fix!
