### ISSUE TITLE
get_matches for distribution based matching fails with error "len(ranks) < 2"

### ISSUE THREAD

**Issue by Anphisa** [delftdata/valentine#46]
Hello,

I ran Valentine with the DistributionBased strategy

```
import pandas as pd
from valentine.algorithms import DistributionBased
from valentine import valentine_match

df1 = pd.read_csv("data/Climate data/recent/wetter_tageswerte_00164_akt/Geographie_Stationsname/Metadaten_Geographie_00164.csv", encoding='utf-8')
df2 = pd.read_csv("data/Climate data/recent/wetter_tageswerte_00164_akt/Geographie_Stationsname/Metadaten_Stationsname_00164.csv", encoding='utf-8')

matches = valentine_match(df1, df2, DistributionBased())
```

And I get this error:
[![Unbenannt4.png](https://i.postimg.cc/3JxZZ27t/Unbenannt4.png)](https://postimg.cc/kDL8J62S)
(RuntimeError: len(ranks) < 2)

The csv files come from here: https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/weather_phenomena/recent/. I converted the data to csvs. I'll attach my csvs: 
[Metadaten_Geographie_00164.csv](https://github.com/delftdata/valentine/files/9819987/Metadaten_Geographie_00164.csv)
[Metadaten_Stationsname_00164.csv](https://github.com/delftdata/valentine/files/9819988/Metadaten_Stationsname_00164.csv)
(Overview and explanation of data: https://www.dwd.de/EN/ourservices/cdc/cdc_ueberblick-klimadaten_en.html)

I'm on Windows 10, I've forked valentine and am running it locally. It is up to date with valentine:master today. I haven't made any changes to the DistributionBased code.

**Comment by kPsarakis** [comment]
Hello, thanks a lot for letting us know. We managed to reproduce the issue, and currently working on a fix.

**Comment by kPsarakis** [comment]
Hi, I pushed a fix for this issue, take a look if it works now. It was caused because the data had some empty columns, and a quantile histogram could not be defined. Now we just skip the creation of histograms in that case. 

A general recommendation, in the absence of data, an instance-based algorithm like `DistributionBased` might be sub-optimal, you could try the default version of  `Coma`  in such a case that works based on the schema information.

**Comment by Anphisa** [comment]
Hello, thanks again for the quick answer & fix! It works now.

And of course your remark makes sense. I'm currently running multiple algorithms to compare results, so I wanted to use DistributionBased as well. I assume it won't perform as well (in this case, it can't) as the schema-based algorithms.
