### ISSUE TITLE
get_matches for distribution based matching fails with error "'charmap' codec can't encode character..."

### ISSUE THREAD

**Issue by Anphisa** [delftdata/valentine#49]
Hello,

I ran Valentine with the DistributionBased strategy
```
import pandas as pd
from valentine.algorithms import DistributionBased
from valentine import valentine_match

df1 = pd.read_csv("data/Geodata/location_cities_countries/cities.csv", encoding='utf-8')
df2 = pd.read_csv("data/Geodata/location_cities_countries/countries.csv", encoding='utf-8')

matches = valentine_match(df1, df2, DistributionBased())
```

And I get this error:
![image](https://user-images.githubusercontent.com/15688223/196914818-b3fde2fb-ba85-4fcc-90df-d0feb97d665b.png)
(UnicodeEncodeError: 'charmap' codec can't encode character '\u0103' in position 4: character maps to <undefined>)

The csv files come from here: https://www.kaggle.com/datasets/liewyousheng/geolocation

I'm on Windows 10, I've forked valentine and am running it locally. It is up to date with valentine:master today. I haven't made any changes to the DistributionBased code.

**Comment by kPsarakis** [comment]
Hi again, I pushed a fix for that. The reason was windows being windows not having the utf-8 encoding as default (needed because there are emojis in your dataset), and we had to specify it.

**Comment by Anphisa** [comment]
Hello, thank you again for your quick help! Now I get no more bugs with the DistributionBased strategy, not even when there are emojis in the dataset 😄
