### ISSUE TITLE
wrong column pkl filename with DistributionBased matching

### ISSUE THREAD

**Issue by cchristodoulaki** [delftdata/valentine#53]
Hello, and thank you for the library! 🍾 

When using `DistributionBased` matching, I have the following use case:
- I create an instance of the matcher. I have two source tables (`source_1` and `source_2`), and one target table `target`.
- I call `matcher.get_matches(source_1, target)`. Pickle files for columns of `source_1` and `target` tables are written to e.g., `/tmp/tmpkpakbdjz`, and the same files are read back with `clustering_utils.get_column_from_store`. Matches are generated.
- I call `matcher.get_matches(source_2, target)`. Pickle files for columns of `source_2` and `target` tables are written to e.g., `/tmp/tmp41gf90n2`. HOWEVER, `clustering_utils.get_column_from_store` attempts to read pkl files created for columns of **`source_1`** from directory `/tmp/tmp41gf90n2`

**Comment by kPsarakis** [comment]
Hello! Thank you for reporting this.

I will try to push a fix in the coming days.
