### ISSUE TITLE
COMA returns empty results if java is not installed, making test assertions fail for the wrong reason

### ISSUE THREAD

**Issue by Archer6621** [delftdata/valentine#58]
Tested on MacOS 13.6 (Ventura).

This also affects other parts of the test suite that may use COMA, causing assertions to fail.

Probably the right course of action would be to throw an exception if COMA cannot be ran properly on the system, which can then be caught in the tests to make the user aware of this.

**Comment by Dome-s** [comment]
i am currently getting a similar issue where COMA instance based returns no found matches for some of the datasets, probably due to an error i would assume but no error is being thrown.

**Comment by kPsarakis** [comment]
@Dome-s COMA instance could also produce empty lists if it cannot find matches. If the Jar throws an exception, this propagates to Python. It does not generate an empty list. 

Could you share any of the datasets?

**Comment by kPsarakis** [comment]
@Dome-s, you are correct. These datasets do not produce output because Java runs out of memory. Try to increase the java_xmx parameter of the Coma matcher default: "1024m". 

We will create better error messages for this. Thanks for reporting this!

**Comment by kPsarakis** [comment]
This has been addressed in the latest release (v0.1.9) thanks a lot @Archer6621 and @Dome-s for pointing out this issue.
